### ISSUE TITLE
there is a way easer :)

### ISSUE THREAD

**Issue by jt3k** [ilyaigpetrov/copy-unicode-urls#1]
`navigator.clipboard.writeText(decodeURIComponent(location))`
:D

**Comment by ilyaigpetrov** [comment]
Do you suggest this line of code instead of whole `copyToClipboard(localizeUrl(url))` or just instead of  `copyToClipboard`?

**Comment by jt3k** [comment]
Вместо целого кода, исключая места навешивания обработчиков и где указываются области клика

Я не вижу проблему которую решает весь скрипт, потому как сделаный мною когда-то букмарк работал хорошо всегда.

javascript:navigator.clipboard.writeText(decodeURIComponent(location))

translated -=---=-=-=-=
Instead of the whole code, excluding places for adding event handlers and where click areas are indicated

I don’t see the problem that the whole script solves, because the bookmark I made once worked well always.

**Comment by ilyaigpetrov** [comment]
`decodeURIComponent('https://example.com?foo=%26&bar=baz')` will result in `https://example.com?foo=&&bar=baz` which is incorrect.

**Comment by jt3k** [comment]
Becaus source string is incorrect

**Comment by ilyaigpetrov** [comment]
Could you, please, elaborate. Do you say that some specification prohibits such urls as `https://example.com?foo=%26&bar=baz`? What exactly is wrong with it?

**Comment by jt3k** [comment]
it seems that to decode urls of this kind correctly, you need to use decodeURI

```js
decodeURI('https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%9B%D0%B5%D0%B2%D0%B5%D0%BD%D1%88%D1%82%D0%B5%D0%B9%D0%BD%D0%B0?foo=%26&bar=baz'); // => "https://ru.wikipedia.org/wiki/Расстояние_Левенштейна?foo=%26&bar=baz"
```

**Comment by ilyaigpetrov** [comment]
I agree, that's why I use `decodeURI`, not `decodeURIComponent`.
