### ISSUE TITLE
It does not work from mouse-menu

### ISSUE THREAD

**Issue by toplinden** [ilyaigpetrov/copy-unicode-urls#13]
I click right mouse button over some link and select from appeared menu: „Copy Unicode URL”. Then I past by mouse-menu or <kbd>Ctrl</kbd><kbd>V</kbd> anywhere but it would be something that I copied before like from <kbd>Ctrl</kbd><kbd>C</kbd>. 

It worked a time ago but it was stopped.

Some infos:
- Google Chrome 88.0.4324.182
- Copy Unicode URLs 0.0.14

**Comment by ilyaigpetrov** [comment]
Thank you for the report.
Fixed in 0.0.15, published to webstore -- already available.
