### ISSUE TITLE
Link to text

### ISSUE THREAD

**Issue by toplinden** [ilyaigpetrov/copy-unicode-urls#15]
Last versions of Chrome have new option which allow get a link to text:

<details><summary>It works so</summary> 

You select text and click on button from mouse's menu
![image](https://user-images.githubusercontent.com/8969612/122453447-0bdc1380-cfb3-11eb-86f7-1a011025b763.png)

But you get

<pre>https://uk.wikipedia.org/wiki/%D0%9F%D0%B0%D0%B1%D0%BB%D0%BE_%D0%95%D1%81%D0%BA%D0%BE%D0%B1%D0%B0%D1%80#:~:text=%D0%BE%D0%B4%D0%BD%D0%BE%D0%BC%D1%83%20%D0%B7%20%D0%B3%D0%BE%D1%82%D0%B5%D0%BB%D1%96%D0%B2.-,%D0%9A%D1%96%D0%BD%D0%B5%D1%86%D1%8C,-%D0%BA%D0%B0%D1%80%27%D1%94%D1%80%D0%B8%20%D1%82%D0%B0%20%D0%B7%D0%B0%D0%B3%D0%B8%D0%B1%D0%B5%D0%BB%D1%8C</pre>

While I prefer unicode, so

<pre>https://uk.wikipedia.org/wiki/Пабло_Ескобар#:~:text=одному%20з%20готелів.-,Кінець,-кар'єри%20та%20загибель</pre>

</details>

**Comment by ilyaigpetrov** [comment]
[copy-unicode-urls-0.0.16-test0.zip](https://github.com/ilyaigpetrov/copy-unicode-urls/files/6749461/copy-unicode-urls-0.0.16-test0.zip) --, please, test it. Instructions on installing a zipped extension are in the [README](https://github.com/ilyaigpetrov/copy-unicode-urls/blob/master/README.md).

**Comment by ilyaigpetrov** [comment]
Implemented and published in 0.0.16 in the webstore and on https://github.com/ilyaigpetrov/copy-unicode-urls/releases.
