### ISSUE TITLE
Chrome extension stopped working

### ISSUE THREAD

**Issue by qarkai** [ilyaigpetrov/copy-unicode-urls#18]
Since v0.0.19, right after new 'Clipboard rewrite' permission notification.
Also disappeared from context menu.

**Comment by ilyaigpetrov** [comment]
Have you tried reinstalling it?

**Comment by ilyaigpetrov** [comment]
Or you may also send me the logs:
1) Open chrome://extensions.
2) Switch on "Developer mode".
3) Find the extension.
4) Press "Inspect views: background page".
5) Select the console tab if it isn't selected already.
6) Resize the window and make screenshots.

**Comment by ilyaigpetrov** [comment]
Please, send the logs before reinstalling the extension. Thanks.

**Comment by ilyaigpetrov** [comment]
Thanks for the report, I have submitted a fix in 0.0.20.  
Here is the news: https://github.com/ilyaigpetrov/copy-unicode-urls/issues/17#issuecomment-1119305563.  

Please, submit a screenshot of the logs anyway: it may occur that you have some different bug.

**Comment by toplinden** [comment]
I had the same problem with 0.0.19. Reistalling didnʼt help. If I correctly understood instruction then thereʼs a screenshot of this.

![image](https://user-images.githubusercontent.com/8969612/167104829-6406c74d-45a4-4137-9c0e-99c3fb488bd4.png)
