### ISSUE TITLE
Place "Ю" icon in Firefox address bar

### ISSUE THREAD

**Issue by BrontoRed** [ilyaigpetrov/copy-unicode-urls#19]
It's been a while since last update, but maybe you can add an option to place "Ю" icon in Firefox address bar?

**Comment by ilyaigpetrov** [comment]
Do you mean: "an option to move "Ю" icon in Firefox address bar?"
Like it's depicted here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction.

**Comment by BrontoRed** [comment]
Yes, I think it's more intuitive to have actions associated with urls in address bar.

**Comment by ilyaigpetrov** [comment]
Page action feature was [dropped in Chromium's MV3](https://developer.chrome.com/docs/extensions/reference/pageAction/) and is [planned to be merged into unified `action` API in the future FireFox releases](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/):
> Firefox retains the page action API, key, and special shortcut in the developer preview but will merge the page action features into action in a later release.

If page action feature will find its way into MV3 or later standards, please, reopen this issue.
