### ISSUE TITLE
Ambiguous %25 in encoded IRI

### ISSUE THREAD

**Issue by jakubklimek** [ilyaigpetrov/copy-unicode-urls#2]
With version 0.0.3 (Chrome Web Store)
This IRI: 
`https://data.gov.cz/formulář/registrace-datové-sady?url=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FOstrava%2F37085111` is incorrectly copied as 
`https://data.gov.cz/formulář/registrace-datové-sady?url=https%253A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FOstrava%2F37085111`

Note the extra `%25` after `url=https`

**Comment by ilyaigpetrov** [comment]
Fixed in https://github.com/ilyaigpetrov/copy-unicode-urls/commit/6b8105edbacba122a706f78ff8746b7e633964f4 which was published to webstore as 0.0.5.

**Comment by ilyaigpetrov** [comment]
Extension was removed from WebStore for missing an icon (which is obviously present in the extension package). It will take some time before I republish it.

**Comment by ilyaigpetrov** [comment]
0.0.6 was published in WebStore.
