### ISSUE TITLE
can not copy URL in edge

### ISSUE THREAD

**Issue by Brian099** [ilyaigpetrov/copy-unicode-urls#20]
edge version  114.0.1823.67

**Comment by ilyaigpetrov** [comment]
Hi. I've checked the extension on Edge under Linux.
Could you, please, provide a step by step algorithm which demonstrates the issue.

Here is how it works for me:
![cuu-edge-howto](https://github.com/ilyaigpetrov/copy-unicode-urls/assets/1090811/55bfdbac-edad-43b5-a018-41c83fdf8039)

**Comment by Brian099** [comment]
sorry, I try again, it works, thanks.
