### ISSUE TITLE
Replace %20 to space

### ISSUE THREAD

**Issue by 0x391F** [ilyaigpetrov/copy-unicode-urls#21]
For example, I copy 
https://www.baidu.com/s?word=%E7%91%9E%E5%85%B8%20%E5%8C%97%E7%BA%A6, it becomes
https://www.baidu.com/s?word=瑞典%20北约, but it should be [https://www.baidu.com/s?word=瑞典&nbsp;北约](https://www.baidu.com/s?word=瑞典&nbsp;北约)

**Comment by ilyaigpetrov** [comment]
If you drop the final link with spaces into an email then the link is truncated by spaces -- that's why I encode them.
What is your use case, where do you need to preserve spaces?
