### ISSUE TITLE
About browser.urlbar.decodeURLsOnCopy

### ISSUE THREAD

**Issue by alurm** [ilyaigpetrov/copy-unicode-urls#22]
You mention that on Firefox browser.urlbar.decodeURLsOnCopy can be prefered in some situations.

While this is true, you could also specify that the extension has certain advantages (well, changes in behaviour, technically) over browser.urlbar.decodeURLsOnCopy.

I think that you can mention that browser.urlbar.decodeURLsOnCopy, for example, doesn't convert spaces to %20.

That means that the copied text won't be treated as a link by many text preprocessors (Discord, Telegram, GitHub, Markdown, and so on).

This is a selling point for me.

Also, curiously, Firefox Android doesn't have access to about:config and in Firefox Android Nightly browser.urlbar.decodeURLsOnCopy doesn't work.

This is also a selling point for me.

You may want to mention that the extension has some of these benefits over browser.urlbar.decodeURLsOnCopy.

Thanks for the extension!

**Comment by Jiang10086** [comment]
> You mention that on Firefox browser.urlbar.decodeURLsOnCopy can be prefered in some situations.
> 
> While this is true, you could also specify that the extension has certain advantages (well, changes in behaviour, technically) over browser.urlbar.decodeURLsOnCopy.
> 
> I think that you can mention that browser.urlbar.decodeURLsOnCopy, for example, doesn't convert spaces to %20.
> 
> That means that the copied text won't be treated as a link by many text preprocessors (Discord, Telegram, GitHub, Markdown, and so on).
> 
> This is a selling point for me.
> 
> Also, curiously, Firefox Android doesn't have access to about:config and in Firefox Android Nightly browser.urlbar.decodeURLsOnCopy doesn't work.
> 
> This is also a selling point for me.
> 
> You may want to mention that the extension has some of these benefits over browser.urlbar.decodeURLsOnCopy.
> 
> Thanks for the extension!

Thanks for your mention this feature, I have enabled it, now I can copy directly on address bar.
