### ISSUE TITLE
Copying directly from Omnibox

### ISSUE THREAD

**Issue by K0media** [ilyaigpetrov/copy-unicode-urls#3]
Am I doing something wrong or it doesn't work this way?
I mean, I got a link from RU Wikipedia for example and it still show as punylinks when directly copied from Omnibox.

Example URL: https://ru.wikipedia.org/wiki/Заглавная_страница

Copying with a trailing space on Firefox works fine, but not anymore for Chrome. That's why I'm using this extension.

Is is meant to copy and decode links only within a webpage or can it be done via Omnibox too? That would be much more clever if you could copy directly from Omnibox without encoding.
That's the whole point of this extension... Right?
Or does it work only inside web pages?

Can the Omnibox feature be added, if possible?

Please advise.

**Comment by ilyaigpetrov** [comment]
Hi, @K0media. To copy decoded url from address bar to buffer you have to click the icon of the extension with a left mouse button. Maybe later I will be able to add a shortcut for this, yet I'm not sure if it's possible.

**Comment by ilyaigpetrov** [comment]
Will `Ctrl+Shift+U` fit your needs?
You can suggest other shortcuts, rules are here: https://developer.chrome.com/apps/commands.

**Comment by ilyaigpetrov** [comment]
`Ctrl+Shift+U` is already taken on Linux for entering Unicode symbols. We need some other shortcut.

**Comment by ilyaigpetrov** [comment]
https://github.com/ilyaigpetrov/copy-unicode-urls/releases/tag/0.0.8 -- in this version you may use Ctrl+Shift+Y. It is not yet published to webstore, publishing to webstore may take weeks.

**Comment by K0media** [comment]
`Ctrl+Shift+Y` is used by my password manager, Bitwarden for a quick password generation tool.
I was thinking about `Ctrl+Shift+C` but it's used by another software I use.
What about `Shift+Alt+C` or `Shift+Alt+T`? 
It's your decision.

**Comment by K0media** [comment]
But as you mentioned, left-clicking the extension icon works. I just wanted to make sure it shows at least a tooltip or a toast that the link was copied to the clipboard.
That's the least that can be done here in order to alert the user that the link was copied to the clipboard.

**Comment by ilyaigpetrov** [comment]
`Alt+Shift` switches keyboard layouts on my system. What about `Alt+U`?

**Comment by K0media** [comment]
Yeah, I think `Alt+U` works. I know that `Ctrl+U` shows the page source code. But maybe Alt+U should do the job.

A few markdown editors use that shortcut, but it's not a crucial one. You can look up furthermore if you want. But `Alt+U` seems like a good deal.

**Comment by ilyaigpetrov** [comment]
`Alt+U` was added since v0.0.8.
