### ISSUE TITLE
Add locale support

### ISSUE THREAD

**Issue by TotalCaesar659** [ilyaigpetrov/copy-unicode-urls#5]
Please add locale support for translating to other languages.

**Comment by ilyaigpetrov** [comment]
I'm currently busy with other projects. But you may make a pull request and I will take a look.

**Comment by ilyaigpetrov** [comment]
Shipped in v0.0.11 in [the webstore](https://chrome.google.com/webstore/detail/copy-unicode-urls/fnbbfiapefhkicjhecnoepbijhanpkjp).
Thank you.
